project:
  type: website
  output-dir: docs

website:
  title: "Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/prteek

format:
  html:
    theme: cosmo
    css: styles.css
